Algoritmo "resposta"

Var

   opcao : inteiro

Inicio

      repita
            escreval("1-Dizer olá")
            escreval("2-Dizer oi")
            escreval("0-Sair do programa")
            leia(opcao)
            se (opcao = 1) entao
               escreval("Olá - Tudo bem?")
            fimse
             se (opcao = 2) entao
               escreval("Oi - Como você está?")
            fimse
      ate (opcao = 0)

Fimalgoritmo